#! /bin/sh
#
# chklog --- Generate summery of Gaussian log file
#

me=`echo "$0" | sed -e 's,.*/,,'`

usage="\
Usage: $0 [OPTION]

Output the summery of Gaussian log file.

Operation modes:
  -h, --help         print this help, then exit
  -z, --zero         show zero-point energy only"

help="
Try \`$me --help' for more information."

GREPOPT="("out" "of")|("SCF" "Done")|Converged| NO | YES|exceeded|("zero-point" "Energies")|("Optimization" "completed")|("thermal" "Enthalpies")|("thermal" "Free" "Energies")|("with" "non" "electrost")|("all" "non" "electrost")|("Total" "free" "energy" "in" "sol.")|("ONIOM:" "extrapolated" "energy")|("imaginary" "frequencies")|  UMP4"

# Parse command line
while test $# -gt 0 ; do
  case $1 in
    --help | --h* | -h )
       echo "$usage"; exit 0 ;;
    --zero | -z )
       GREPOPT="("zero-point" "Energies")"
       shift ; break;;
    --energy | -e )
       GREPOPT="("SCF" "Done")|("Zero-point" "correction")|("Thermal" "correction" "to" "Enthalpy")|Corr|("E2" "=")|UMP4|CCSD"
       shift ; break;;
    -* )
       echo "$me: invalid option $1$help"
       exit 1 ;;
    * )
       break ;;
  esac
done

if test $# == 0; then
    echo "Please specify the Gaussian log file!"
    exit 1
fi

egrep "$GREPOPT" $1
chklog1 $1

