#!/bin/bash

#Welcome to GenCC, mindlessly helping you automate Coupled Cluster since 2024-08-29!
#Written because none of us can be bothered to do it by hand, by Christian Drew Knox, for the Peng Liu Group
#WARNING! THIS SCRIPT USES pg2xyz AS A DEPENDENCY!

bname=`echo $1 | sed -e 's/.log//g'`
bname=`echo $bname | sed -e 's/.out//g'`

mem='24GB'
nproc=12

#PLEASE remember to change the charge!!!
charge='0 1'

#ORCA has a lot of formatting differences. Until I find a more efficient way to do this, this will do.
ccsd1="! aug-cc-pVTZ aug-cc-pVTZ/C DLPNO-CCSD(T) TightSCF NormalPNO CPCM"
ccsd2="%cpcm smd true"
ccsd3='	  SMDsolvent "thf"'
suffix7='_ccsdSP'
#PLEASE edit the CCSD(T) charge and multiplicity as well!!!
ccsd4="* xyz 0 1"

#This code block is copied directly from GenBench
oname=$bname$suffix7

echo '%pal nprocs 16' > $oname.inp
echo 'end' >> $oname.inp
echo $ccsd1 >> $oname.inp
echo $ccsd2 >> $oname.inp
echo $ccsd3 >> $oname.inp
echo 'end' >> $oname.inp
echo '%maxcore 6000' >> $oname.inp
echo "$ccsd4" >> $oname.inp
pg2xyz.g09 $1 >> $oname.inp
echo '*' >> $oname.inp
echo '' >> $oname.inp

echo 'Generated DLPNO-CCSD(T) job'

qorca.smp $bname$suffix7.inp

echo 'Submitted DLPNO-CCSD(T) job'