#!/bin/bash

bname=`echo $1 | sed -e 's/.log//g'`
bname=`echo $bname | sed -e 's/.out//g'`

mem='24GB'
nproc=12
charge='0 1'
#method1='m06/genecp scrf=(smd,solvent=decalin-mixture)'
#method1='m06/genecp scrf=(smd,solvent=acetonitrile)'
#method1='m06/genecp scrf=(smd,solvent=toluene) EmpiricalDispersion=gd3'
#method1='m06/genecp scrf=(smd,solvent=toluene)'
#method1='m06/genecp scrf=(solvent=2-propanol,read,smd)'
#method1='m06/genecp scrf=(smd,solvent=n,n-DiMethylFormamide)'
#method1='m06/genecp scrf=(smd,solvent=thf)'
#method1='m06/genecp scrf=(smd,solvent=dichloromethane)'
#method1='m06/genecp scrf=(smd,solvent=2-methoxyethanol)'
#method1='m06/genecp scrf=(smd,solvent=Tetrahydrofuran) stable=opt'
#method1='m06/genecp'
method1='opt freq m062x'

#atoms1='C H N O S'
#atoms1='C H -O -N -F -Br -Cl -Si'
#atoms2='-Cs -Ni -I'
basis1='6-31G(d)'
#basis2='SDD'

#########################################################################
#########################################################################

oname=$bname'_SPSC'
ctrline=$method1


echo '%mem='$mem       > $oname.com
echo '%nproc='$nproc  >> $oname.com
echo '#p '$ctrline     >> $oname.com
echo ''               >> $oname.com
echo 'single point SMD solvation model calculation' >> $oname.com
echo ''               >> $oname.com
echo $charge          >> $oname.com
pg2xyz $1             >> $oname.com
#echo ' '              >> $oname.com

echo $atoms1' 0'      >> $oname.com
echo $basis1          >> $oname.com
echo '****'           >> $oname.com
echo $atoms2' 0'      >> $oname.com
echo $basis2          >> $oname.com
echo '****'           >> $oname.com
echo ''               >> $oname.com
echo $atoms2' 0'      >> $oname.com
echo $basis2          >> $oname.com

echo ''              >> $oname.com

# HFIP definition
#echo 'stoichiometry=C3H2F6O1'              >> $oname.com
#echo 'solventname=HFIP'              >> $oname.com
#echo 'eps=16.7'              >> $oname.com
#echo 'rsolv=4.6'              >> $oname.com
#echo ''              >> $oname.com

#########################################################################
#########################################################################

echo 'Generated 1 SCRF input files!'

#qg09 $bname'-SP'.com ishared 144
#qg16 $bname'_SPSC'.com
# qg09.trestles $bname'-SPdcm'.com

#echo 'Submitted 1 job!'

