#! /bin/sh
#
# energies from Gaussian output files
#

filename=`basename $1`

### Initializing ###
ID='N/A'
formula='N/A'
E1='N/A'
E2='N/A'
E3='N/A'
E4='N/A'
ECPCM1='N/A'

ID=`echo $filename | /usr/bin/awk -F_ '{print $1}'`
formula=`grep "Stoichiometry" $1 | tail -1 | /usr/bin/awk '{print $2}'`

E1=`grep "extrapolated energy" $1 | tail -1 | /usr/bin/awk '{print $5}'`
if [ "$E1" == "" ]; then
  E1=`grep "SCF Done" $1 | tail -1 | /usr/bin/awk '{print $5}'`
fi
E2=`grep "zero-point Energies" $1 | tail -1 | /usr/bin/awk '{print $7}'`
E3=`grep "thermal Enthalpies" $1 | tail -1 | /usr/bin/awk '{print $7}'`
E4=`grep "thermal Free Energies" $1 | tail -1 | /usr/bin/awk '{print $8}'`

#cpcmfilename='smd/'$1
cpcmfilename=`echo $1 | sed 's/\./_SP./'`
if [ -r "$cpcmfilename" ]
then
  ECPCM1=`grep "SCF Done" $cpcmfilename | tail -1 | /usr/bin/awk '{print $5}'`
fi
if [ "$ECPCM1" == "" ]; then
  ECPCM1='N/A'
fi

echo "$ID $filename $formula $E1 $E2 $E3 $E4 $ECPCM1"
#echo "$ID $filename $formula $E1 $E2 $E3 $E4"

